version: 2

models:

  - name: base__appsflyer__cost
    description: Appsflyer base model
    columns:
      - name: campaign_id 
        description: '{{ doc("id")}}'
        tests: ['unique', 'not_null']