default:
  before_script:
  # requirements
    - pip3 install -r requirements.txt
    - dbt deps
  # GCP SA credz
    - echo $GITLAB_CI_SA > $DBT_GOOGLE_KEYFILE_PATH_DEV
  # prod manifest
    - python utils/pull_prod_manifest.py
    - export DBT_ARTIFACT_STATE_PATH=./

image: python:3.10-slim-buster

stages:
  - pre-run
  - run
  - test

# cache:
#   paths:
#     - .cache/pip
#     - dbt_packages

variables:
  DBT_PROFILES_DIR: ./
  DBT_USER: $DBT_USER
  GIT_CHECKOUT: "true"

  DBT_GOOGLE_KEYFILE_PATH_DEV: keyfile.json
  DBT_GOOGLE_PROJECT_DEV: ama-dwh-dev
  DBT_BIGQUERY_DATASET_DEV: CI_PR$CI_MERGE_REQUEST_IID

.trigger_rule:
  only: 
    refs: 
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
    changes:
      - models/**/*
      - snapshots/**/*
      - dbt_project.yml
      - packages.yml
      - requirements.txt
      - .gitlab-ci.yml

seed:
  stage: pre-run
  extends: .trigger_rule
  script: dbt seed

check_required_tests:
  stage: pre-run
  extends: .trigger_rule
  script: dbt run-operation required_tests

sqlfluff_lint:
  stage: pre-run
  extends: .trigger_rule
  script: sqlfluff lint

dbt_run:
  stage: run
  extends: .trigger_rule
  script: dbt run --select state:modified+ --defer

dbt_test:
  stage: test
  extends: .trigger_rule
  script: dbt test --select state:modified+ --defer
