version: 2

models:

  - name: base__adwords__cost
    description: Google adwords base model
    columns:
      - name: id
        description: '{{ doc("id")}}'
        tests:
          - unique:
              severity: warn # TODO UUID not found, possible duplicated data
          - not_null